/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_Encrypted_Data_Key_Material    15
#define gattdb_device_information             16
#define gattdb_manufacturer_name_string       18
#define gattdb_model_number_string            20
#define gattdb_hardware_revision_string       22
#define gattdb_firmware_revision_string       24
#define gattdb_system_id                      26
#define gattdb_custom_health_telemetry        29

#define gattdb_generic_attribute_len          2
#define gattdb_service_changed_char_len       4
#define gattdb_database_hash_len              16
#define gattdb_client_support_features_len    1
#define gattdb_device_name_len                13
#define gattdb_Encrypted_Data_Key_Material_len 24
#define gattdb_device_information_len         2
#define gattdb_manufacturer_name_string_len   12
#define gattdb_model_number_string_len        8
#define gattdb_hardware_revision_string_len   3
#define gattdb_firmware_revision_string_len   20
#define gattdb_system_id_len                  8
#define gattdb_custom_health_telemetry_len    8


#endif // __GATT_DB_H
