// Auto-generated by AI/ML extension, do not modify

/***************************************************************************/ /**
 * @file sl_ml_model_bp_model_int8.h
 * @brief Top-level functions and structures for initializing and executing a
 * machine learning model with TensorFlow Lite Micro.
 *******************************************************************************
 * # License
 * <b>Copyright 2025 Silicon Laboratories Inc. www.silabs.com</b>
 *******************************************************************************
 *
 * The licensor of this software is Silicon Laboratories Inc. Your use of this
 * software is governed by the terms of Silicon Labs Master Software License
 * Agreement (MSLA) available at
 * www.silabs.com/about-us/legal/master-software-license-agreement. This
 * software is distributed to you in Source Code format and is governed by the
 * sections of the MSLA applicable to Source Code.
 *
 ******************************************************************************/

#pragma once

#include "sl_ml_tflite_micro_model.h"

#if !defined(SL_ML_ENABLE_DYNAMIC_MODEL_LOAD) || (SL_ML_ENABLE_DYNAMIC_MODEL_LOAD == 0)

#include "bp_model_int8_generated.hpp"

static sl_ml_model_handle_t sl_ml_bp_model_int8_model_handle{
  bp_model_int8,
  bp_model_int8_length,
  &bp_model_int8_op_resolver,
  bp_model_int8_buffers,
  bp_model_int8_buffer_sizes,
  bp_model_int8_buffer_count,
#if !defined(SL_ML_ENABLE_DYNAMIC_MEMORY_ALLOCATION) || (SL_ML_ENABLE_DYNAMIC_MEMORY_ALLOCATION == 0)
  4,
  nullptr
#else
  bp_model_int8_model_buffer_alignment,
  bp_model_int8_model_buffer_sections
#endif
};

#else

// In case of profiling a dynamically loaded model, the model is loaded using pre-defined memory regions.
// For implementation, see sl_ml_profiler_helper.cc.
#define DYNAMIC_MODEL
static sl_ml_model_handle_t sl_ml_bp_model_int8_model_handle{
  nullptr,
  0,
  nullptr,
  nullptr,
  nullptr,
  0,
  0,
  nullptr
};
#endif